[tools]
nodejs = "22.19.0"

[env]
NODE_ENV = "development"

[tasks.install]
description = "Install dependencies"
run = "npm install"

[tasks.build]
description = "Build the project"
run = "npm run build"

[tasks.dev]
description = "Start development server"
run = "npm run start"

[tasks.test]
description = "Run tests"
run = "npm test"

[tasks.lint]
description = "Run linter"
run = "npm run lint"

[tasks.format]
description = "Format code"
run = "npm run format"

[tasks.cli]
description = "Run CLI"
run = "npm run cli"

[tasks.example]
description = "Run example configuration"
run = "npm run start:example"

[tasks.clean]
description = "Clean build artifacts"
run = "npm run build:clean"

[tasks.release-patch]
description = "Release a patch version"
run = "npm run release:patch"

[tasks.release-minor]
description = "Release a minor version"  
run = "npm run release:minor"

[tasks.release-major]
description = "Release a major version"
run = "npm run release:major"

[tasks.release-dry]
description = "Dry run publish to test package"
run = "npm run release:dry"

[tasks.publish-check]
description = "Check if package is ready for publishing"
run = "npm run prepublishOnly"